### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by rprasanth** [clearlinux/bsdiff#13]
Hi, I could see the failures in the test script, I suspect the binary loaded in the source got some issue while syncing in the github.
Could you verify and update the test data?

```
/bsdiff-1.0.4/test$ sh run.sh 
Running test #8 ...
Failed to apply delta (-1)
not ok 4 - 
Running test #10 ...
Failed to apply delta (-1)
diff: 10.out: No such file or directory
not ok 6 - output does not match expected!!
```

**Comment by phmccarty** [comment]
The test suite is meant to be run with `make check` in the toplevel source directory. Can you try that instead to see if it works for you?

I see that it would be convenient to call `run.sh` directly, so I'll add a feature request.

**Comment by rprasanth** [comment]
Got the same with make check, "Failed to apply delta (-1)" which shows the issue with the samples under data.
Didn't you see this issue?

```
====================================
   bsdiff 1.0.4: ./test-suite.log
====================================

# TOTAL: 11
# PASS:  9
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test/run
==============

Running test #5 ...
ok 1
PASS: test/run.sh 1
Running test #6 ...
ok 2
PASS: test/run.sh 2
Running test #7 ...
ok 3
PASS: test/run.sh 3
Running test #8 ...
Failed to apply delta (-1)
not ok 4 - 
FAIL: test/run.sh 4 -
Running test #9 ...
ok 5
PASS: test/run.sh 5
Running test #10 ...
diff: 10.out: No such file or directory
Failed to apply delta (-1)
not ok 6 - output does not match expected!!
FAIL: test/run.sh 6 - output does not match expected!!
Running test #11 ...
ok 7
PASS: test/run.sh 7
Running test #12 ...
ok 8
PASS: test/run.sh 8
Running test #13 ...
ok 9
PASS: test/run.sh 9
Running test #15 ...
Failed to create delta (-1)
ok 10
PASS: test/run.sh 10
Running test #16 ...
ok 11
PASS: test/run.sh 11
1..11
```

**Comment by phmccarty** [comment]
No, I've never seen those tests fail. Before I make new releases, I run `make distcheck`, so test failures would have blocked the release process.

Note that I primarily run these tests on Clear Linux OS.

Which distro are you using? I would like to try and reproduce the issue.

**Comment by rprasanth** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Comment by rprasanth** [comment]
could find the dependecies lzma and bzip2 helps the test, As they were sample binary data, couldn't see the root cause. Thanks
